apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: n8n
  namespace: n8n
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`n8n.crussell.io`) # Change this to your domain
      kind: Rule
      services:
        - name: n8n
          port: 80
  tls:
    certResolver: letsencrypt
