apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`longhorn.internal.crussell.io`)
      kind: Rule
      services:
        - name: longhorn-frontend
          port: 80
