---
# PodMonitor for detailed application pod metrics
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: application-pods
  namespace: monitoring
  labels:
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - forgejo
      - jellyseerr
      - paperless-ngx
      - mealie
      - ntfy
      - open-webui
      - radarr
      - sonarr
      - prowlarr
      - jackett
      - qbittorrent
      - karakeep
      - it-tools
      - n8n
  selector: {}
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      path: /metrics
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
          action: keep
          regex: "true"
        - sourceLabels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
          action: replace
          targetLabel: __metrics_path__
          regex: (.+)
        - sourceLabels:
            [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          targetLabel: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - sourceLabels: [__meta_kubernetes_namespace]
          action: replace
          targetLabel: kubernetes_namespace
        - sourceLabels: [__meta_kubernetes_pod_name]
          action: replace
          targetLabel: kubernetes_pod_name
        - sourceLabels: [__meta_kubernetes_pod_container_name]
          action: replace
          targetLabel: kubernetes_container_name

---
# PodMonitor for media applications (special handling for torrenting metrics)
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: media-apps-pods
  namespace: monitoring
  labels:
    app: prometheus
spec:
  namespaceSelector:
    matchNames:
      - radarr
      - sonarr
      - prowlarr
      - jackett
      - qbittorrent
  selector:
    matchLabels:
      app.kubernetes.io/component: media
  podMetricsEndpoints:
    - port: http
      interval: 60s
      path: /metrics
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_namespace]
          targetLabel: media_namespace
        - sourceLabels: [__meta_kubernetes_pod_label_app_kubernetes_io_name]
          targetLabel: media_app
