apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nas
  namespace: external-services
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`nas.internal.crussell.io`)
      kind: Rule
      services:
        - name: nas-external
          port: 80 
