apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
  - namespace.yaml
  - external-nas.yaml
  - external-homeassistant.yaml
  - ingress-nas.yaml
  - ingress-homeassistant.yaml
