apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-services
resources:
  # Home Assistant
  - external-homeassistant.yaml
  - ingress-homeassistant.yaml

  # NAS
  - external-nas.yaml
  - ingress-nas.yaml

  # qBittorrent
  - external-qbittorrent.yaml
  - ingress-qbittorrent.yaml

  # Jellyfin
  - external-jellyfin.yaml
  - ingress-jellyfin.yaml

  # MinIO
  - external-minio.yaml
  - ingress-minio-api.yaml
  - ingress-minio-web.yaml

  # Namespace
  - namespace.yaml
