apiVersion: v2
name: qdrant
description: Qdrant - Vector Database for the next generation of AI applications.
type: application
version: 0.1.0
appVersion: "v1.15.4"
home: https://qdrant.tech/
icon: https://qdrant.tech/images/logo.svg
sources:
  - https://github.com/qdrant/qdrant
keywords:
  - qdrant
  - vector
  - database
  - ai
maintainers:
  - name: Qdrant Team
    email: info@qdrant.tech
dependencies:
  - name: qdrant
    version: 1.15.4
    repository: https://qdrant.github.io/qdrant-helm