apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: qdrant
  namespace: qdrant-system
spec:
  interval: 15m
  chart:
    spec:
      chart: qdrant
      version: "1.15.4"
      sourceRef:
        kind: HelmRepository
        name: qdrant
        namespace: flux-system
      interval: 15m
  values:
    image:
      repository: qdrant/qdrant
      tag: v1.15.4
      pullPolicy: IfNotPresent

    # Distributed setup with 3 replicas
    replicas: 3

    # Configuration for Qdrant
    config:
      cluster:
        enabled: true
      service:
        type: ClusterIP
        
    # Resource limits and requests
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"

    # Storage configuration using Longhorn
    persistence:
      enabled: true
      storageClass: "longhorn"
      accessModes:
        - ReadWriteOnce
      size: 10Gi

    # Service configuration
    service:
      type: ClusterIP
      port: 6333
      grpcPort: 6334

    # Probes configuration
    probes:
      liveness:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      readiness:
        enabled: true
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 3
      startup:
        enabled: true
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
        failureThreshold: 30