apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qdrant
  namespace: qdrant-system
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qdrant.internal.crussell.io`)
      kind: Rule
      services:
        - name: qdrant
          port: 6333
  tls:
    certResolver: letsencrypt