# Default values for qdrant.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

qdrant:
  # Qdrant image
  image:
    repository: qdrant/qdrant
    tag: v1.15.4
    pullPolicy: IfNotPresent

  # Number of replicas for distributed setup
  replicas: 3

  # Configuration for Qdrant
  config:
    cluster:
      enabled: true
    service:
      # For a distributed setup, you might need to change this depending on your environment
      type: ClusterIP
      
  # Resource limits and requests
  resources:
    requests:
      memory: "512Mi"
      cpu: "250m"
    limits:
      memory: "2Gi"
      cpu: "1000m"

  # Storage configuration
  persistence:
    enabled: true
    storageClass: "longhorn"
    accessModes:
      - ReadWriteOnce
    size: 10Gi

  # Service configuration
  service:
    type: ClusterIP
    port: 6333
    grpcPort: 6334

  # Probes configuration
  probes:
    liveness:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    readiness:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
    startup:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 30

# Additional configurations for the namespace
namespace:
  name: qdrant-system
  create: true