apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 15m
  values:
    # Global image settings
    image:
      tag: "v1.135.3"

    # Environment variables
    env:
      TZ: "America/New_York"
      # Database configuration - using your existing PostgreSQL
      DB_HOSTNAME: "postgres-cluster-rw.postgres-system.svc.cluster.local"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "immich"
      DB_VECTOR_EXTENSION: "pgvector"
      # Upload location
      UPLOAD_LOCATION: "/usr/src/app/upload"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: db-username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: db-password

    # Immich configuration
    immich:
      persistence:
        # Library storage - we'll create a PVC with NFS
        library:
          existingClaim: immich-library

    # Server configuration
    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: "v1.135.3"

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 2Gi

      # Probes
      probes:
        liveness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /api/server/ping
              port: 2283
            initialDelaySeconds: 30
            periodSeconds: 30
        # readiness:
        #   enabled: true
        #   custom: true
        #   spec:
        #     httpGet:
        #       path: /api/server/ping
        #       port: 2283
        #     initialDelaySeconds: 15
        #     periodSeconds: 10

    # Machine Learning service
    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: "v1.135.3"

      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 4Gi

      persistence:
        cache:
          enabled: true
          size: 10Gi
          storageClass: "longhorn"
          accessMode: ReadWriteOnce

      # Proper health checks for machine-learning (runs on port 3003)
      probes:
        liveness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 60
            periodSeconds: 30
        readiness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
        startup:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /ping
              port: 3003
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30

    # Redis (internal)
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          size: 1Gi
          storageClass: "longhorn"

    # Service configuration
    service:
      server:
        ports:
          http:
            port: 2283
      machine-learning:
        ports:
          http:
            port: 3003

    # Ingress will be handled separately
    ingress:
      main:
        enabled: false

    # Security context for all containers
    securityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch

    # Pod security context
    podSecurityContext:
      runAsUser: 999
      runAsGroup: 999
      fsGroup: 999
      fsGroupChangePolicy: OnRootMismatch
