apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: "0.9.3"
      sourceRef:
        kind: HelmRepository
        name: immich
        namespace: immich
      interval: 15m
  values:
    # Global image settings
    image:
      tag: "v1.122.3"

    # Environment variables
    env:
      TZ: "America/New_York"
      # Database configuration - using your existing PostgreSQL
      DB_HOSTNAME: "postgres-cluster-rw.postgres-system.svc.cluster.local"
      DB_PORT: "5432"
      DB_DATABASE_NAME: "immich"
      DB_USERNAME:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: db-username
      DB_PASSWORD:
        valueFrom:
          secretKeyRef:
            name: immich-secrets
            key: db-password

    # Immich configuration
    immich:
      persistence:
        # Library storage using NFS to your NAS
        library:
          enabled: true
          type: nfs
          server: 192.168.20.31
          path: /mnt/tank/photos
          globalMounts:
            - path: /usr/src/app/upload

    # Server configuration
    server:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-server
        tag: "v1.122.3"

      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 2000m
          memory: 2Gi

      # Probes
      probes:
        liveness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /api/server-info/ping
              port: 3001
            initialDelaySeconds: 30
            periodSeconds: 30
        readiness:
          enabled: true
          custom: true
          spec:
            httpGet:
              path: /api/server-info/ping
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10

    # Machine Learning service
    machine-learning:
      enabled: true
      image:
        repository: ghcr.io/immich-app/immich-machine-learning
        tag: "v1.122.3"

      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 2000m
          memory: 4Gi

      persistence:
        cache:
          enabled: true
          size: 10Gi
          storageClass: "longhorn"
          accessMode: ReadWriteOnce

    # Redis (internal)
    redis:
      enabled: true
      architecture: standalone
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          size: 1Gi
          storageClass: "longhorn"

    # Service configuration
    service:
      main:
        controller: server
        ports:
          http:
            port: 3001

    # Ingress will be handled separately
    ingress:
      main:
        enabled: false

    # Default pod options
    defaultPodOptions:
      securityContext:
        fsGroup: 999
        fsGroupChangePolicy: OnRootMismatch
