#ENC[AES256_GCM,data:X8ZDBxYpfRHnF9loi0q50r8mrfImX/o/sWE+PzfFi/B6KZZuKBJO6umr,iv:fed5pCQUufy2sIhUYfzSsJs6asgflZMXYjPYt/bz49Q=,tag:+1B9VqB5Rt3++e3Oy9vwjw==,type:comment]
#ENC[AES256_GCM,data:dwCj7jxHWimuNmTvUYLdIr4PPaFdXRPUDrlWziT9NKlRrOnvx1afn8CMNLQV1i01/v909W2T,iv:YUOs+qP97G53BMiDWmHs2NzMZNA6fEGVIym8EU4C0f0=,tag:DSP7LKzT5SS75AXdNhSoBw==,type:comment]
apiVersion: ENC[AES256_GCM,data:/ik=,iv:sZYqnuhM5t5o0QvI8o+WBx8mS0Li/vswPBiAaweg0Bo=,tag:qeeuquuWccKKjcJRlGwBlw==,type:str]
kind: ENC[AES256_GCM,data:Co1rIAi+,iv:6UoHHCwTGj48xl6EGIecAhKaWqeLDX2I3CnTteIgUGM=,tag:5iTSMwykAP0JbcC5usdhVg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:19yLePww63n6Qffr21E=,iv:1vwe4YxRWih2f1DiuSwpf/PV1wPh2RAL3hlHrkhDz1U=,tag:gSAuFMdxXPiGmDfDyouEBA==,type:str]
    namespace: ENC[AES256_GCM,data:mwXaP8An,iv:s4F84ZtORj7uC0kcFYvuUyrpW8QqjxZF20CyxuepXWg=,tag:sdu4YS24me2GIndl7uDjMw==,type:str]
type: ENC[AES256_GCM,data:kQqmxmHv,iv:mEKxlOl+F9KXD21654ueXRXip7BvRAhi73gsE8B9WVc=,tag:D4xYF2fTm/uXON+/aZkqtQ==,type:str]
stringData:
    db-username: ENC[AES256_GCM,data:oaCAJaPZ,iv:PasniGey2Rvd+EWRbXFhCk/zLl0NB5KXkHAuzg8hKUg=,tag:w2hIi7M7BSLMxw2sp/UvQw==,type:str]
    db-password: ENC[AES256_GCM,data:ymOVU4sLux1GciJFPk0=,iv:noU2NqCF6CUiuF/7Z/44Mg2/PkB5sP1gZMzq0uWvLmM=,tag:S+Qb2UMG/b7i3Iq4VZa4ow==,type:str]
sops:
    age:
        - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OERFVVFOeTduNnZsWS9s
            blFtZU5xVnR0NHM5K1VyL1Bremtac3VNeENrCk5DRXpQTFJiS1dJMEdpay9JN0dk
            ay9xbTArUXR1eTBLVER1QkVGMG0zcGcKLS0tIFZudmlhM1NkVkMxWFRZOTNpQjcy
            WGJzMTJrZ2RsTFQreUVWREtoMSt0MlkKTrFJtKqPAarTSAXVL75pZWsGl6QDEPH9
            R6Ng16cmLLn38pT7Gx42Z4PuwPNf/3OssD9qRJlqc0GeJmdWskmMkQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-25T00:42:42Z"
    mac: ENC[AES256_GCM,data:bCd708GxS9ZE6r3Uw9hqMhUJPxTitLJ7fevaWnHRcatlzjB+bfr/80fjK2WauDeI3AWNF1jm1+7nQI7YsIwusiO1IO7k0p+qqtNtVL9M7s64Z0pvEbvJ1TXP5lFvg88MARDBfWJkykjt1lgR2+TP38P5ekoGqaBeSGX/Iwb2ubQ=,iv:rLiqJEKRMd/8/N5tuVGNqrsubXUxfdaxpXlNxzOICuo=,tag:ctAaoBYl/SHeYhW6E7dhQg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
