apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
resources:
  # Core Infrastructure
  - ./metallb
  - ./longhorn

  # Ingress Controller
  - ./ingress

  # Applications
  - ./apps

  # Secrets - load last
  - ./secrets
