apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: flux-system
resources:
  # Core Infrastructure
  - ./metallb
  - ./longhorn
  - ./capacitor

  # Ingress Controller
  - ./ingress

  # Applications
  - ./apps

  # Database
  - ./postgres

  # Monitoring (CRDs already exist in cluster)
  - ./monitoring
