apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinepods
  namespace: pinepods
spec:
  template:
    spec:
      containers:
      - name: pinepods
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pinepods-db-credentials
              key: password
