apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pinepods
  namespace: pinepods
spec:
  interval: 15m
  chart:
    spec:
      chart: pinepods
      version: "*" # Use latest version to get the most recent fixes
      sourceRef:
        kind: HelmRepository
        name: pinepods
        namespace: pinepods
      interval: 15m
  values:
    # Main application configuration
    image:
      repository: madeofpendletonwool/pinepods
      tag: "latest"
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 8040

    ingress:
      enabled: false

    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 10Gi
      retain: true

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 2Gi

    # Disable built-in PostgreSQL and use external Redis instead of bundled Valkey
    postgresql:
      enabled: false
    valkey:
      enabled: false

    # Podpeople settings
    podpeople:
      enabled: true
      environment:
        ntfyUrl: "http://ntfy.ntfy.svc.cluster.local"

    # Application environment
    env:
      USERNAME: "admin"
      PASSWORD: "pinepods"
      FULLNAME: "Admin User"
      EMAIL: "admin@local.lan"
      DEBUG_MODE: "false"
      HOSTNAME: "https://pinepods.internal.crussell.io"
      DB_HOST: "postgres-cluster-rw.postgres-system.svc.cluster.local"
      DB_USER: "pinepods"
      DB_NAME: "pinepods"
      DB_PORT: "5432"
      DB_TYPE: "postgresql"
      VALKEY_HOST: "redis.redis.svc.cluster.local"
      VALKEY_PORT: "6379"
      DB_PASSWORD: "fHVrbPHDYdw5FE"

    # Health check configuration to allow more time for startup
    livenessProbe:
      initialDelaySeconds: 180
      periodSeconds: 30
      timeoutSeconds: 10
      failureThreshold: 5
    readinessProbe:
      initialDelaySeconds: 180
      periodSeconds: 15
      timeoutSeconds: 10
      failureThreshold: 5
