apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pinepods
  namespace: pinepods
spec:
  interval: 15m
  chart:
    spec:
      chart: pinepods
      version: "*" # Use latest version to get the most recent fixes
      sourceRef:
        kind: HelmRepository
        name: pinepods
        namespace: pinepods
      interval: 15m
  values:
    # Main application configuration
    image:
      repository: madeofpendletonwool/pinepods
      tag: "latest"
      pullPolicy: IfNotPresent

    service:
      type: ClusterIP
      port: 80

    ingress:
      enabled: false

    persistence:
      enabled: true
      storageClass: "longhorn"
      accessMode: ReadWriteOnce
      size: 10Gi
      retain: true

    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 2Gi

    # Disable built-in PostgreSQL and Redis (we'll use external services)
    postgresql:
      enabled: false
    valkey:
      enabled: false

    # Podpeople settings
    podpeople:
      enabled: true
      environment:
        ntfyUrl: "http://ntfy.ntfy.svc.cluster.local"

    # Application environment
    env:
      USERNAME: "admin"
      PASSWORD: "pinepods"
      FULLNAME: "Admin User"
      EMAIL: "admin@local.lan"
      DEBUG_MODE: "false"
      HOSTNAME: "https://pinepods.internal.crussell.io"
