apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pinepods
  namespace: pinepods
spec:
  interval: 15m
  chart:
    spec:
      chart: pinepods
      version: "3.2.1" # NOTE: Pinning chart version for stability
      sourceRef:
        kind: HelmRepository
        name: pinepods
        namespace: pinepods
      interval: 15m
  values:
    pinepods:
      image:
        repository: ghcr.io/pinepods/pinepods
        tag: "latest" # Consider pinning to a specific version in production
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: false # We will manage ingress separately with an IngressRoute
      persistence:
        enabled: true
        storageClass: "longhorn"
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 2Gi

    postgresql:
      enabled: false # Disable the included PostgreSQL

    valkey:
      enabled: false # Disable the included Redis/Valkey

    externalDatabase:
      host: "postgres-cluster-rw.postgres-system.svc.cluster.local"
      port: 5432
      user: "pinepods"
      database: "pinepods"
      sslmode: "disable"
      password:
        secretName: pinepods-db-credentials
        secretKey: password

    externalRedis:
      host: "redis.redis.svc.cluster.local"
      port: 6379
      password: "" # Assuming no password for the internal Redis
