apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - database-service.yaml
  - external-redis-service.yaml
  - ingress.yaml


