apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - database-service.yaml
  - external-redis-service.yaml
  - ingress.yaml
  - secrets.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: pinepods
    path: db-password-patch.yaml

