apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: librechat
  namespace: librechat
spec:
  interval: 1h
  url: https://raw.githubusercontent.com/danny-avila/LibreChat/gh-pages/

