apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: librechat
  namespace: librechat
spec:
  interval: 15m
  chart:
    spec:
      chart: ./helm/librechat
      sourceRef:
        kind: GitRepository
        name: librechat
        namespace: librechat
      interval: 15m
  values:
    replicaCount: 1
    global:
      librechat:
        existingSecretName: "librechat-credentials-env"
        existingSecretApiKey: CHADGPT_API_KEY
    librechat:
      configEnv:
        PLUGIN_MODELS: Qwen3-4B-Instruct-2507-GGUF,nomic-embed-text-v2-moe-GGUF,gpt-oss-120b-mxfp-GGUF,GLM-4.5-Air-UD-Q4K-XL-GGUF,user.Qwen3-Coder-30B-A3B-Instruct-GGUF
        DEBUG_PLUGINS: "true"
        ALLOW_REGISTRATION: "true"
        ALLOW_SOCIAL_LOGIN: "true"
        DOMAIN_SERVER: "https://librechat.internal.crussell.io"
        DOMAIN_CLIENT: "https://librechat.internal.crussell.io"
        TRUST_PROXY: "1"
      existingSecretName: "librechat-credentials-env"
      configYamlContent: |
        version: 1.2.9
        endpoints:
          custom:
            - name: "ChadGPT"
              type: openai
              apiKey: "${CHADGPT_API_KEY}"
              baseURL: "http://192.168.20.132:8000/v1"
              models:
                default:
                  - "qwen3-coder-30b-a3b-instruct-q8"
                fetch: true
              titleModel: "qwen3-coder-30b-a3b-instruct-q8"
              summarize: false
              modelDisplayLabel: "ChadGPT"
            - name: "OpenRouter"
              type: openai
              apiKey: "${OPENROUTER_API_KEY}"
              baseURL: "https://openrouter.ai/api/v1"
              models:
                default:
                  - "openrouter/auto"
                fetch: true
              titleModel: "openrouter/auto"
              summarize: false
              modelDisplayLabel: "OpenRouter"
      imageVolume:
        enabled: true
        size: 10G
        accessModes: ReadWriteOnce
    mongodb:
      enabled: true
      auth:
        enabled: false
      databases:
        - LibreChat
    meilisearch:
      enabled: true
      persistence:
        enabled: true
        storageClass: ""
      image:
        tag: "v1.7.3"
      auth:
        existingMasterKeySecret: "librechat-credentials-env"
    ingress:
      enabled: false
