apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: librechat
  namespace: librechat
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`librechat.crussell.io`)
      kind: Rule
      services:
        - name: librechat
          port: 3080
  tls:
    certResolver: letsencrypt