apiVersion: ENC[AES256_GCM,data:WEM=,iv:2Zl4HRAmpaYk377wIInDT3+R6dNiaPzAb+KbBLA6GAY=,tag:SPQU65VkYec7TcvaT+W1Jw==,type:str]
kind: ENC[AES256_GCM,data:ocVF9bXY,iv:0UQ+EKw2fllWQxzoKjo4HbS1E40enlPAcgCvjJihqAM=,tag:DZV2zFAKrwMt1ixmOBvpLA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:b2y7TpSaXKT/KV+5H1+gZnj5Vi2kXx13zA==,iv:hs88y6Bc0aBxh98QPVW/+u5eFJ+4UuQ4VoTcPipvcAs=,tag:cRcYr7DxSBwM8TpWqiyfmQ==,type:str]
    namespace: ENC[AES256_GCM,data:eaAK8iM+SxC1,iv:TKiS6/Tc5cDJGbq7zAdJmuXEH6PGhccHy1G46qZ5ZYk=,tag:Rr3f2tRWtTzRKs0mep7IsA==,type:str]
type: ENC[AES256_GCM,data:KvWWCmEr,iv:IYd6OHnzf5u39S0we4LMgwctGmiFzvAW3cZZENgPyvU=,tag:KUa7nVop2KHmd32RSNUgjg==,type:str]
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:hoMUoZRurngwWRooyhxZeMkzt9RhaJ5GB78Y1DthKFzy+fhkBFbdqF4M7iCttiT68M4kZYwSVv2RfLeh6Su+rA==,iv:P6WZhniY+IoW55z6G/y5m6B55vnfV7DZAVbBlMFvROc=,tag:SfovLIEzdDw16PFY6DGJmQ==,type:str]
    CREDS_IV: ENC[AES256_GCM,data:QGmL54MRXWFikZ1N4qSzAZ+GyWeLSUJjy819ElbX4NA=,iv:frraUGdGKUlUW3wRGaW6PFyeLrvLrOUnvoNbfi3tcaQ=,tag:cXxJL7eoG9BoLAC4ZNTajw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:/4w5zA7Sop3dvZWm2+XIoKB7i3x98DJtQshQQ5RoszAYRX6FzfaMUw0aacf6s76XyWlBPFDiNNA+QQTtsYMR0w==,iv:EjV3diuF992P9fy3ITjOO5vX/5pe2guPhMLq9cI/b5s=,tag:2DZ3lifXtuDN7D0aKMUFZQ==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:w5H8G+6Crag1UyL1q2zANvweoCvQ0PPeRQzROJhsmss81HwWHdN7Bq6tAG6Q+UQVX7YyBUqQrzOG9lFTZMzcOw==,iv:R7weDS+JQNVybjrMb9gm0VAThijpDljcMTQ4zQocxwg=,tag:uGZWV2OdOsZh2D5LjVckZQ==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:iz5Inzq7PVrvWGl8/FmsiLLam+PjrsPtWc/OsbCFNSIoVm9WFcc3qR/oLUE=,iv:t03W1YgG2LB+uH1zY/iIpqsOBQU8JaiKLexFe67FHFs=,tag:ozFjRw/IiOZ4aIL1boIVKQ==,type:str]
sops:
    age:
        - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzlHc1J4Um02K3M0aDRt
            M1oxdmFxSXFvcmp4VXN6NXlxL2FYUlVZRUZBCkIxR0NBNitHSkRnMExUTmJyR3Ja
            RUQ1eHM2UCs2K1VVUk1pMG5YRzV4SlUKLS0tIDVpaHlIUC81Nk9hejhqaURvMkFZ
            WWRnTmdiQlpVTDZYWXJVa3VUaHJEMWsKlbBoVXK3YtzStZ94GNgQe7yEki19Mm8e
            lsVCKNGKUH0oBXzWPT+G8+3jLIOKDjr5PnXQKbabAH2ysU5mJGxR4w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-22T22:39:19Z"
    mac: ENC[AES256_GCM,data:Cbisc1p6FjRuR6WYHGheA4tOk8xputWG250Tokdr2CB134S3KvaEopb51KFwM2imfQKZxbZxD6M65o3UR0j+xeFCEDt81WgUf6gui/Xp1Ag10tT+GIwDvfeJVpZJqEM1oaPv477YgafErKGl2PotTSC2HosglOGzO8MFolZgKfY=,iv:E5sciwl2bgD2QQKTt7+7lXiejNGISqlWWOiGajfi4wg=,tag:XlGZp1XjqSx9AlHhkz5IPg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
