apiVersion: ENC[AES256_GCM,data:n6I=,iv:qWosbNOlHRYYGhxBaZ1TSf6NxLM3M5ZTZ0I+jP+cVZ0=,tag:g2uMvf2o4PzwGS6RTCt6Pw==,type:str]
kind: ENC[AES256_GCM,data:ovoWpJQk,iv:qbLWo58ZNw+mKG6egwlJUc4n6q9gm6LQOjvwKEnqpQA=,tag:mdwcdwrDrhcsBPao3iSgow==,type:str]
metadata:
    name: ENC[AES256_GCM,data:zsGLZ87tLT6/DBdOM9acGaH4LSd10p+TLg==,iv:44jxEkrKzW/Pv+ddg2iuxRlGJHyfONO8NpBHcBQpEOQ=,tag:k3ZSfus0fN8V6e9yaZs4/A==,type:str]
    namespace: ENC[AES256_GCM,data:w2Ckg7pchor1,iv:qSyYoO7FcY5iVRKJiYrk0eDT2xCRNZJgMSs0VbKlZWM=,tag:4UhY+I1lP4l9udPhVSZ4xg==,type:str]
type: ENC[AES256_GCM,data:wNE5NoiY,iv:WoP52rg7QlmlnJfclmgW49/MxNplg/1QFfuozfhh/CI=,tag:cS3/zQ6QoOCgZn6jUaFueg==,type:str]
stringData:
    CREDS_KEY: ENC[AES256_GCM,data:MC4YzY0Wwb7s6U7zkK8/l96kx2thP+M4Y8xQxn7tdBTcNvhi03bw6IWJZYGG4tmycCI/NGOdeWJvnMQb/gYZ1g==,iv:X0XJpPOytHlGvrGO04lEASNURIO0TSw6q5JbOmmGc1c=,tag:28m0Codor1oElkG9ry3Tmg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:VibBQm1ws4TNwlOTc+yd3h8L7Lg2UOrnLDCrQfcsv2UjhQmxbffr2fv8+Ht2XSCGdOf6y5ZI/9k3p1PMh2UGmA==,iv:TJdcKyWo7vplXShmUgYlJpJtziiseynCUppwNTmOV9o=,tag:U/rtPnckmr2NAzJ83BHSpQ==,type:str]
    JWT_REFRESH_SECRET: ENC[AES256_GCM,data:gWjitc0wFg+zncaJD2lQvt3WZa66iRK1zZ/ukc8cg4tpp4eogi3CvxPal9DVu8jgs2G+PPiH25zTgDSMtP1oCQ==,iv:zk+vbins2ZTTiZpj7KiTDuvxu1FRSxyBsLudJqSA1G0=,tag:kHcFoqNbjIn2pUFnEp8YKw==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:KW4icGJ1K2y4ga3APTChwV2g+xxm2cZO4Wjfm65mbp5uIJfsDwlNVyKfUSOQtHW/8R6b8WadHg7e5iKlZM+C4A==,iv:PtGLi3X9Ar3lueRKtFCrb/soN4hrEmPftmVeUfRNfFM=,tag:bYFkLFkLL0KFKxAu0DPr9Q==,type:str]
    CHADGPT_API_KEY: ENC[AES256_GCM,data:DczErjqoDE0=,iv:Km9zituGY5e+6a2enqDEkZIw5cXmkJzwyggxdWQJa9w=,tag:JBPHp8PC0Zit8azaeTR6KQ==,type:str]
    OPENROUTER_API_KEY: ENC[AES256_GCM,data:WNuj33bnd20j0RMQQm0xBm189LfuGUKbcw/QTg+16wQr/1zXA+IzZU+e7In11ZaXntiqAsnphG6HzxbE59lisipz1YaoE6SR9Q==,iv:TMh87e8kBLSurpE+1SW65vDvc585VyuU4Sg9oTK3QvU=,tag:4f2VErHkJrF45evSKvwVwA==,type:str]
sops:
    age:
        - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dGJkTWhKUzhTc1cxd2N2
            L0l2MzZ3QzltNFoxZHFMcXNjTG00dHUzSVh3CjR5bXNCVjVhTzhZTGV4OW9PMFlJ
            SWpLRVo2OVRWZ2VPd3JpaTBSV1E0bmMKLS0tIE5RbEdiRU1sZ2xLVFhPNExvT3py
            UjArRWZaaTZKaWtqanZnU0FveFl2d1kKYfjgLFN0jcyD7oIz1lF1074rhWZJwzvs
            gl5w/xjR1NSxXtm7INnIqE1nmDjcjPPKaFHo8LuooAy36bNbljOkDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T17:39:39Z"
    mac: ENC[AES256_GCM,data:u1Mz7pj7rgrF93J/JgVjDYqsL6/1PPd4Jnc7mOZd/CJZb6WP8bxReS5zl5RlseoLbFZpIBjHXmjtKzYbQlBW6sQEHVFp5ehyEVOXCXTJ/8UAgNjrRtW9Ok9eudc9D00ig/3Mc+Ajg0bbQZs/dCciwOcTN6FO9kpZ+6SzODeEZIc=,iv:EwwfIYV3bnqTsXMeqCRRAkgGVU3s1E6qSYLxf5P3C9w=,tag:k1KmwxvHOPcqFPkYXvt+aA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
