apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: uptime-kuma
spec:
  interval: 5m
  chart:
    spec:
      chart: uptime-kuma
      version: 2.21.3
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: uptime-kuma
  values:
    persistence:
      enabled: true
      size: 1Gi
