apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: n8n
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: "1.0.7"
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: n8n
      interval: 15m
  values:
    # Ingress configuration (adjust domain to match your setup)
    ingress:
      enabled: true
      className: "nginx" # Adjust if you use a different ingress class
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod" # Adjust if needed
      hosts:
        - host: n8n.local # Change this to your domain
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: n8n-tls
          hosts:
            - n8n.local # Change this to your domain

    # Main n8n application configuration
    main:
      # Basic configuration
      replicaCount: 1

      # n8n specific configuration
      config:
        n8n:
          host: "n8n.local" # Change this to your domain
          port: 5678
          protocol: "https"
        webhook:
          url: "https://n8n.local" # Change this to your domain

      # Service configuration
      service:
        type: ClusterIP
        port: 80

      # Persistence for workflows and data
      persistence:
        enabled: true
        type: dynamic
        storageClass: "longhorn" # Using your Longhorn storage
        accessModes:
          - ReadWriteOnce
        size: 10Gi

      # Resource limits (adjust based on your needs)
      resources:
        limits:
          cpu: 1000m
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 512Mi
