apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jackett
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media
      interval: 15m
  values:
    controllers:
      jackett:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/jackett
              tag: "ghcr.io/home-operations/jackett:0.22.2441" # {"$imagepolicy": "flux-system:jackett"}
            env:
              TZ: "America/New_York" # Change to your timezone
              AUTO_UPDATE: "true"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 9117
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  tcpSocket:
                    port: 9117
                  initialDelaySeconds: 10
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        fsGroup: 65534 # nobody group
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: jackett
        ports:
          http:
            port: 9117
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "longhorn" # Using your Longhorn storage
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /config
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
