apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: jackett-headers
  namespace: media
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
      X-Forwarded-Port: "443"
      X-Forwarded-Host: "jackett.internal.crussell.io"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jackett
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jackett.internal.crussell.io`)
      kind: Rule
      services:
        - name: jackett
          port: 9117
      middlewares:
        - name: jackett-headers
  tls:
    certResolver: letsencrypt
