apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis
  namespace: redis
spec:
  interval: 5m
  chart:
    spec:
      chart: redis
      version: 22.0.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: redis
  values:
    architecture: standalone
    auth:
      enabled: false
    master:
      persistence:
        enabled: true
        storageClass: longhorn
        size: 2Gi
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
    service:
      type: ClusterIP
      port: 6379