apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secrets.yaml
  - config-secret.yaml
  - server-configs.yaml
  - service.yaml
  - deployment.yaml
  - ingress.yaml
