# Karakeep Main Application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
  namespace: karakeep
  labels:
    app: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      containers:
        - name: karakeep
          image: ghcr.io/karakeep-app/karakeep:release
          ports:
            - containerPort: 3000
          env:
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: nextauth-secret
            - name: NEXTAUTH_URL
              value: "https://karakeep.k3s.crussell.io"
            - name: MEILI_ADDR
              value: "http://meilisearch:7700"
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: meili-master-key
            - name: BROWSER_WEB_URL
              value: "http://chrome:9222"
            - name: DATA_DIR
              value: "/data"
            - name: TZ
              value: "America/New_York"
            # Add OpenAI key if you want AI tagging
            # - name: OPENAI_API_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: karakeep-secrets
            #       key: openai-api-key
          volumeMounts:
            - name: karakeep-data
              mountPath: /data
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: karakeep-data
          persistentVolumeClaim:
            claimName: karakeep-data
---
# Meilisearch for Karakeep
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: karakeep
  labels:
    app: meilisearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
        - name: meilisearch
          image: getmeili/meilisearch:v1.13.3
          ports:
            - containerPort: 7700
          env:
            - name: MEILI_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: karakeep-secrets
                  key: meili-master-key
            - name: MEILI_NO_ANALYTICS
              value: "true"
          volumeMounts:
            - name: meilisearch-data
              mountPath: /meili_data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 7700
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: meilisearch-data
          persistentVolumeClaim:
            claimName: meilisearch-data
---
# Chrome for web scraping
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrome
  namespace: karakeep
  labels:
    app: chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
        - name: chrome
          image: gcr.io/zenika-hub/alpine-chrome:123
          ports:
            - containerPort: 9222
          command:
            - --no-sandbox
            - --disable-gpu
            - --disable-dev-shm-usage
            - --remote-debugging-address=0.0.0.0
            - --remote-debugging-port=9222
            - --hide-scrollbars
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "300m"
          livenessProbe:
            httpGet:
              path: /json/version
              port: 9222
            initialDelaySeconds: 30
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /json/version
              port: 9222
            initialDelaySeconds: 10
            periodSeconds: 10
---
# Persistent Volume Claims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
# Services
apiVersion: v1
kind: Service
metadata:
  name: karakeep
  namespace: karakeep
  labels:
    app: karakeep
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: karakeep
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: karakeep
  labels:
    app: meilisearch
spec:
  ports:
    - port: 7700
      targetPort: 7700
  selector:
    app: meilisearch
---
apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: karakeep
  labels:
    app: chrome
spec:
  ports:
    - port: 9222
      targetPort: 9222
  selector:
    app: chrome
