apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - namespace.yaml
  - crds
  - prometheus
  - grafana
  - node-exporter
  - exporters
  - servicemonitors
  - podmonitors

  # PodMonitors (will skip for now - CRD doesn't exist)
  # - podmonitors/application-pods.yaml
