apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

resources:
  - config.yaml
  - prometheus.yaml
  - namespace.yaml
  - grafana
  - node-exporter
  - servicemonitors
  - exporters

  # PodMonitors (will skip for now - CRD doesn't exist)
  # - podmonitors/application-pods.yaml
