apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - redis.yaml
  - gotenberg.yaml
  - tika.yaml
  - deployment.yaml
  - ingress.yaml
  - paperless-ai-deployment.yaml
  - paperless-ai-ingress.yaml
