apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-ai
  namespace: paperless-ngx
  labels:
    app: paperless-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-ai
  template:
    metadata:
      labels:
        app: paperless-ai
    spec:
      containers:
        - name: paperless-ai
          image: clusterzx/paperless-ai:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: paperless-ngx-secrets
          env:
            - name: PAPERLESS_AI_PORT
              value: "3000"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: RAG_SERVICE_URL
              value: "http://localhost:8000"
            - name: RAG_SERVICE_ENABLED
              value: "true"
            - name: PAPERLESS_API_URL
              value: "http://paperless-ngx:8000/api"
          volumeMounts:
            - name: paperless-ai-data
              mountPath: /app/data
          resources:
            requests:
              memory: "1Gi"
              cpu: "200m"
            limits:
              memory: "3Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: paperless-ai-data
          persistentVolumeClaim:
            claimName: paperless-ai-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-ai-data
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: paperless-ai
  namespace: paperless-ngx
  labels:
    app: paperless-ai
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: paperless-ai
