apiVersion: apps/v1
kind: Deployment
metadata:
  name: paperless-gpt
  namespace: paperless-ngx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paperless-gpt
  template:
    metadata:
      labels:
        app: paperless-gpt
    spec:
      containers:
        - name: paperless-gpt
          image: icereed/paperless-gpt:latest
          ports:
            - containerPort: 8080
          env:
            # Paperless-NGX Configuration
            - name: PAPERLESS_BASE_URL
              value: "http://paperless-ngx:8000"
            - name: PAPERLESS_PUBLIC_URL
              value: "https://paperless-gpt.internal.crussell.io"
            - name: PAPERLESS_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: paperless-ngx-secrets
                  key: PAPERLESS_API_TOKEN

            # Tag Configuration
            - name: MANUAL_TAG
              value: "paperless-gpt"
            - name: AUTO_TAG
              value: "paperless-gpt-auto"
            - name: AUTO_OCR_TAG
              value: "paperless-gpt-ocr-auto"

            # LLM Configuration (Ollama Local)
            - name: LLM_PROVIDER
              value: "ollama"
            - name: LLM_MODEL
              value: "gemma3:latest"
            - name: OLLAMA_HOST
              value: "http://192.168.20.119:11434"
            - name: LLM_LANGUAGE
              value: "English"
            - name: TOKEN_LIMIT
              value: "20000"

            # OCR Configuration (Ollama-based)
            - name: OCR_PROVIDER
              value: "llm"
            - name: VISION_LLM_PROVIDER
              value: "ollama"
            - name: VISION_LLM_MODEL
              value: "llava:13b"
            - name: OCR_PROCESS_MODE
              value: "image"
            - name: PDF_SKIP_EXISTING_OCR
              value: "false"

            # OCR Processing Options
            - name: OCR_LIMIT_PAGES
              value: "5"
            - name: CREATE_LOCAL_HOCR
              value: "false"
            - name: CREATE_LOCAL_PDF
              value: "false"
            - name: PDF_UPLOAD
              value: "false"
            - name: PDF_REPLACE
              value: "false"
            - name: PDF_COPY_METADATA
              value: "true"
            - name: PDF_OCR_TAGGING
              value: "true"
            - name: PDF_OCR_COMPLETE_TAG
              value: "paperless-gpt-ocr-complete"

            # Application Configuration
            - name: PORT
              value: "8080"
            - name: LOG_LEVEL
              value: "info"

          volumeMounts:
            - name: paperless-gpt-data
              mountPath: /app/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: paperless-gpt-data
          persistentVolumeClaim:
            claimName: paperless-gpt-data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-gpt-data
  namespace: paperless-ngx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
