apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`ntfy.internal.crussell.io`) # Change this to your domain
      kind: Rule
      services:
        - name: ntfy
          port: 80
