apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: searxng
spec:
  interval: 15m
  chart:
    spec:
      chart: searxng
      version: "1.0.7" # Updated to the latest available version
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: searxng
      interval: 15m
  values:
    # Disable built-in ingress - we'll use Traefik IngressRoute instead
    ingress:
      enabled: false

    # Image configuration - Using 'latest' as 1.0.1 tag was not found
    image:
      tag: "latest" # App version corresponding to chart 1.0.7

    # Main SearXNG application configuration
    replicaCount: 1

    # Service configuration
    service:
      type: ClusterIP
      port: 8080 # Default port for SearXNG

    # SearXNG specific configuration
    # NOTE: The 'config.settings.data' value MUST be a single string containing the entire
    #       SearXNG 'settings.yml' file content.
    #       Please replace the 'secret_key' value with a strong, randomly generated string.
    #       Example command to generate a key: openssl rand -hex 32
    config:
      settings:
        enabled: true
        data: |
          # General settings
          general:
            instance_name: "My SearXNG Instance"
            contact_url: "mailto:admin@crussell.io" # Update if you have a contact
            enable_admin: false # Set to true if you need admin features
            default_doi_resolver: 'oadoi.org' # Fix for KeyError: 'default_doi_resolver'
          
          # Search settings
          search:
            safe_search: 0 # 0 = None, 1 = Moderate, 2 = Strict
            max_results: 20
            
          # Server settings
          server:
            port: 8080
            bind_address: "0.0.0.0"
            secret_key: "84420c2dda3c7ab9c6b17f00a5cc86289d0b7cdb748a96fc1f2f15981922def8"
            base_url: false # Typically handled by ingress
            
          # UI settings
          ui:
            static_use_hash: true
            
          # Outgoing requests settings
          outgoing:
            request_timeout: 5.0
            max_request_timeout: 15.0
            
          # Enabled engines (example, customize as needed)
          # Fix for "engine" field missing errors
          engines:
            - name: google
              engine: google
              shortcut: go
              enabled: true
            - name: duckduckgo
              engine: duckduckgo
              shortcut: ddg
              enabled: true
            # Add more engines as desired
            
          # Preferences (example)
          preferences:
            lock: []
          
          # Tokens (if using)
          tokens: {}
          
          # Categories (if customizing)
          categories: []
          
          # Stats (if enabling)
          stats: false
          
      limiter:
        enabled: true # Enable IP limiter
      
      uwsgi:
        enabled: true # Enable UWSGI

    # Resource limits (adjust based on your needs)
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
