apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: searxng
  namespace: searxng
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`searxng.internal.crussell.io`) # Update if needed
      kind: Rule
      services:
        - name: searxng
          port: 80
  tls:
    certResolver: letsencrypt