apiVersion: ENC[AES256_GCM,data:xWo=,iv:tdShT5kn0nGwFcYC4o/PS9HbVf8LK8Xw1i5l7+IMMNw=,tag:IcvtEB4GM6L8EIGA7PJp6w==,type:str]
kind: ENC[AES256_GCM,data:9/3XNyVl,iv:YthVUD+ILWbjD79ae4m/xQiSt4iXpwoyugJWQmVfCgY=,tag:2ziD74OjcRS79ZGrWKw9fQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:p1qxVVXyhKEdqBsfis7gp+YtEQ==,iv:411vCpDZNHLOmQtkyCxERvWY6jw6IR604Z5y6mbLFn8=,tag:GGoXv5I3azHIV3eRjFMKpw==,type:str]
    namespace: ENC[AES256_GCM,data:izYzdy91Ew==,iv:ifCRVUKCUUzY2B4hp5bFE4P0DpA7SyCVst7noRiG1DU=,tag:uPP0ZkiJl3r9/jT9oO7mtg==,type:str]
type: ENC[AES256_GCM,data:cy99fsnW,iv:RqwDf0khuFyLsx5sfBUkJ1lmAXGZtjUAdKnqoXP89r8=,tag:tBq5IQzH/kZItnv349h3SA==,type:str]
stringData:
    email: ENC[AES256_GCM,data:6Zm5aD3v9Lc8yH2mFsCcMQvoWZz9Een9h8ZDjQ==,iv:ol47mC/1Ku97Or8AzgVKIGJTo4Bn49tFJEimyazZfkk=,tag:xOnc0rlAiJrlVKM30jEKYA==,type:str]
    password: ENC[AES256_GCM,data:q8PZNXIsx4vu+fC/Nxw=,iv:8tw/LC3irA8gO2em+GNg8/uwi70uYNUREU+27r/QEy0=,tag:xM0jeBysAyGFVrT2Wr8DNg==,type:str]
sops:
    age:
        - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aWRWUUYwdzhhMTE4c3Zs
            SWRqdEtUalFUaXpWVlR2OTdVNWhvTFVWZXlVCjUvN3dOdXh6RlRpY1JORjNzODFa
            S3NjcFFhSFpITHBnbzJMQUlzMDdTK0kKLS0tIE9tWnJEZFo4a2s4SWxDMzR4a1R2
            SXI3eWRLQWtKZXR0U3hnTVVNbDBEWWMKxh+stkIcO81JARe0rc5YQqSlpFQEzPja
            tsWqemIdqpQJm4OpLOFTjnGk5SGUdbQMPhYPhbyeGHSy+5XSOuTuWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-11T18:26:57Z"
    mac: ENC[AES256_GCM,data:rgTilRY1EmQzEolA7lf6Ug3/kQRt8JlUERaObvYW5nBOGAlD1gSetzohHxsOtPrKlWrvL3UJdVbjpWT3J79cvlkTlV7s6EXb9Tmu9T6d1lSfYtSd+iLXv4begbIWOBE4hrFjNLXfL51atUABu9wWLAlVkazBrz9ET+nWNNbZ1dg=,iv:wZHO7F/vt2Ac9C+yQlxV60jvzkYXGHknWjg7TAhSvN4=,tag:O9Mb9+IsmytBf1LEcs5RqQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
