apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: it-tools
  namespace: it-tools
spec:
  entryPoints:
    - websecure
  routes:
  tls:
    certResolver: letsencrypt
    - match: Host(`ittools.internal.crussell.io`)
      kind: Rule
      services:
        - name: it-tools
          port: 80
