apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo
  namespace: forgejo
spec:
  interval: 15m
  chart:
    spec:
      chart: forgejo
      version: "11.0.1"
      sourceRef:
        kind: HelmRepository
        name: forgejo
        namespace: forgejo
      interval: 15m
  values:
    # Disable built-in ingress - we'll use Traefik IngressRoute instead
    ingress:
      enabled: false

    # Main Forgejo application configuration
    replicaCount: 1

    # Image configuration
    image:
      registry: code.forgejo.org
      repository: forgejo/forgejo
      rootless: true

    # Forgejo specific configuration
    gitea:
      config:
        # Server configuration
        server:
          DOMAIN: "forgejo.internal.crussell.io" # Change this to your domain
          ROOT_URL: "https://forgejo.internal.crussell.io" # Change this to your domain
          HTTP_PORT: 3000
          SSH_DOMAIN: "forgejo.internal.crussell.io" # Change this to your domain
          SSH_PORT: 22
          SSH_LISTEN_PORT: 2222 # Rootless container uses 2222

        # Database configuration (using external HA PostgreSQL)
        database:
          DB_TYPE: postgres
          HOST: "postgres-cluster-rw.postgres-system.svc.cluster.local:5432"
          NAME: "forgejo"
          USER: "forgejo"
          PASSWD: "v5yMSMqm1NsuZiM7OcFG"
          SSL_MODE: "require"

        # Security settings
        security:
          INSTALL_LOCK: true

        # Repository settings
        repository:
          ROOT: /data/git/repositories

    # Service configuration
    service:
      http:
        type: ClusterIP
        port: 80
      ssh:
        type: ClusterIP
        port: 22

    # Persistence for repositories and data
    persistence:
      enabled: true
      storageClass: "longhorn" # Using your Longhorn storage
      accessModes:
        - ReadWriteOnce
      size: 20Gi

    # Resource limits (adjust based on your needs)
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi

    # Disable built-in PostgreSQL - using external HA PostgreSQL cluster
    postgresql-ha:
      enabled: false

    postgresql:
      enabled: false

    # Use single Redis instead of cluster for simplicity
    redis-cluster:
      enabled: false

    redis:
      enabled: true
      auth:
        enabled: false
      master:
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 5Gi
