apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  namespace: forgejo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`forgejo.internal.crussell.io`) # Change this to your domain
      kind: Rule
      services:
        - name: forgejo-http
          port: 80
