apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo-runners
  namespace: forgejo
spec:
  interval: 15m
  chart:
    spec:
      chart: act-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vquie
        namespace: forgejo
      interval: 15m
  values:
    # Storage configuration - using Longhorn like your main Forgejo deployment
    act_runner:
      storageclass: "longhorn"

      # Forgejo instance URL - should match your Forgejo deployment
      instance: "https://forgejo.internal.crussell.io"

      # Runner registration token - loaded from existing secrets.yaml
      # Generate this from: Site Administration > Actions > Runners > Create Runner
      tokenFromSecret:
        secretName: forgejo-database-secret
        secretKey: RUNNER_TOKEN

      # Runner name/label
      name: "k3s-runner"

      # Runner labels - these determine which jobs this runner can execute
      labels: "ubuntu-latest,ubuntu-22.04,self-hosted"

    # Resource configuration
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi

    # Replica configuration for scaling
    replicaCount: 1

    # Node selector if you want to run on specific nodes
    nodeSelector: {}

    # Tolerations for node taints
    tolerations: []

    # Affinity rules
    affinity: {}
