apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: forgejo-runners
  namespace: forgejo
spec:
  interval: 15m
  chart:
    spec:
      chart: act-runner
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: vquie
        namespace: forgejo
      interval: 15m
    valuesFrom:
      - kind: Secret
        name: forgejo-database-secret
        valuesKey: RUNNER_TOKEN
        targetPath: act_runner.token
  values:
    # Storage configuration - using Longhorn like your main Forgejo deployment
    act_runner:
      storageclass: "longhorn"

      # Forgejo instance URL - should match your Forgejo deployment
      instance: "https://forgejo.internal.crussell.io"

      # Runner labels - these determine which jobs this runner can execute
      labels:
        - "ubuntu-latest:docker://node:16-bullseye"
        - "ubuntu-22.04:docker://node:16-bullseye"
        - "self-hosted:docker://node:16-bullseye"

    # Resource configuration
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 1000m
        memory: 2Gi

    # Replica configuration for scaling
    replicaCount: 1

    # Node selector if you want to run on specific nodes
    nodeSelector: {}

    # Tolerations for node taints
    tolerations: []

    # Affinity rules
    affinity: {}
