apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`sonarr.internal.crussell.io`)
      kind: Rule
      services:
        - name: sonarr
          port: 80
