apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sonarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sonarr.internal.crussell.io`) # Change this to your domain
      kind: Rule
      services:
        - name: sonarr
          port: 80
  tls:
    certResolver: letsencrypt
