apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-temp
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 150Gi
  storageClassName: longhorn
