apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: garage
  namespace: garage
spec:
  interval: 15m
  chart:
    spec:
      chart: contrib/helm/garage
      sourceRef:
        kind: GitRepository
        name: garage
        namespace: garage
      interval: 15m
  values:
    ingress:
      enabled: false
    persistence:
      enabled: true
      existingClaim: garage-nfs-pvc
      accessModes:
        - ReadWriteMany
      size: 500Gi
    # You may want to further configure Garage here (peers, s3, etc.)
