apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - git-repository.yaml
  - helm-release.yaml
  - ingress.yaml
  - ingress-web.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
