apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garage-nfs-pvc
  namespace: garage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
  storageClassName: garage-nfs
