apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - source.yaml
  - release.yaml

configMapGenerator:
  - name: traefik-helm-values
    namespace: traefik
    files:
      - values.yaml=traefik-helm-values.yaml

secretGenerator:
  - name: traefik-helm-secrets
    namespace: traefik
    files:
      - secrets.yaml
    type: Opaque

patchesStrategicMerge:
  - |-
    apiVersion: helm.toolkit.fluxcd.io/v2
    kind: HelmRelease
    metadata:
      name: traefik
      namespace: traefik
    spec:
      valuesFrom:
        - kind: ConfigMap
          name: traefik-helm-values
          valuesKey: values.yaml
        - kind: Secret
          name: traefik-helm-secrets
          valuesKey: secrets.yaml
