apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The order here is important for readability, but kustomize
# is smart enough to create the Namespace and Secrets first.
resources:
  - namespace.yaml
  - source.yaml
  - traefik-helm-values.yaml
  - secrets.yaml
  - release.yaml
  - global-redirect.yaml
