apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Configure SOPS decryption
decryption:
  provider: sops
  secretRef:
    name: sops-age

# The order here is important for readability, but kustomize
# is smart enough to create the Namespace and Secrets first.
resources:
  - namespace.yaml
  - source.yaml
  # Add the real manifests, not generators
  - traefik-helm-values.yaml
  - secrets.yaml
  - release.yaml
