apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      # Find the latest version from https://github.com/traefik/traefik-helm-chart/releases
      version: "27.0.2"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 12h
  # The values will be injected by a kustomize patch
  values: {}
  valuesFrom:
    - kind: ConfigMap
      name: traefik-helm-values
      valuesKey: values.yaml
    - kind: Secret
      name: traefik-helm-secrets
      valuesKey: secrets.yaml
