apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-values
  namespace: traefik
data:
  values.yaml: |
    service:
      type: LoadBalancer
      ports:
        - name: dashboard
          port: 8080
          targetPort: 8080

    replicas: 3
    enableLeaderElection: true

    # Persistent storage for Traefik data
    persistence:
      enabled: true
      name: traefik
      size: 128Mi
      storageClass: "longhorn"
      accessModes:
        - ReadWriteMany
      path: /data
      annotations: {}

    # Use fsGroup to automatically set correct ownership
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"
      runAsGroup: 65532
      runAsNonRoot: true
      runAsUser: 65532

    additionalArguments:
      - "--api.dashboard=true"

    # Enable entryPoints - only HTTP since OPNsense terminates SSL
    entryPoints:
      web:
        address: ":80"
      traefik:
        address: ":8080"
      # websecure removed - OPNsense handles HTTPS

    # Create default IngressClass if not set
    ingressClass:
      enabled: true

    # Ensure service account token is mounted for Kubernetes API access
    automountServiceAccountToken: true


