apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: neo4j
  namespace: neo4j
spec:
  interval: 15m
  chart:
    spec:
      chart: neo4j
      sourceRef:
        kind: HelmRepository
        name: neo4j-helm-charts
        namespace: neo4j
      interval: 1h
  values:
    disableLookups: true
    neo4j:
      name: neo4j
      passwordFromSecret: neo4j-credentials
      acceptLicenseAgreement: "no"
      resources:
        cpu: 500m
        memory: 1Gi
    volumes:
      data:
        mode: dynamic
        dynamic:
          storageClassName: longhorn
          accessModes:
            - ReadWriteOnce
          requests:
            storage: 20Gi
    services:
      neo4j:
        enabled: false
    config:
      server.config.strict_validation.enabled: "false"
    statefulset:
      metadata:
        annotations: {}
    env:
      NEO4J_dbms_security_auth__minimum__password__length: "12"
      NEO4J_dbms_shell_enabled: "false"
    podSpec:
      podAntiAffinity: true
      terminationGracePeriodSeconds: 600
