apiVersion: ENC[AES256_GCM,data:99Y=,iv:HhIwcexgIGqXCzMuT9AFCCgacmpIY+l8lZhpzcJIWY0=,tag:GWwGlNEQyHYcYUj8u28beg==,type:str]
kind: ENC[AES256_GCM,data:uhp09vtD,iv:DhU4VJz6FkNBENReQXGjLSPcoxhwyko41USfU1tBOqQ=,tag:KgMCGRcNv3C9hLy7JVtfXQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:iuqOORNNEbVYbMiVpPbsvR0=,iv:ijooh3VrlOpHwyBlkFqRtUqUTiovckmzmk5030H+oDE=,tag:DyPVm43lFKFjF2DRKDkM+A==,type:str]
    namespace: ENC[AES256_GCM,data:Td0XfJU=,iv:/VXGTqw7RyFW2H3hFmiik4RYOh0Z4AIZM+qw4/mYHPo=,tag:SgBgSOtssUXkqNdK7sZKCg==,type:str]
type: ENC[AES256_GCM,data:ZQm05Wl+,iv:45xwUUs0/tOFOMYZVOfIzbZ2vqo9nnBg8uE1eC9sQZM=,tag:eUNLACbSwBgDSEmgU40Y1g==,type:str]
stringData:
    neo4j-password: ENC[AES256_GCM,data:72beXufj7Gaycln2PRCGPxYRGkeB1AkudoM7YsDLgan8j3DBHrvOZMIQ1DE=,iv:IMxe32wA2rHhcygUu8SjqQr0XyMUHaN1d814LFbwoJo=,tag:38AzpXqtMIOx2pa7CDjCpw==,type:str]
sops:
    age:
        - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVVUdMQ2pHTUZYZVRiMDd0
            UTJGSjB1ZEtuZG16VHV5dXJuU0pvdGVIMHdnCnU4ZUg5L01nR3RIYzk2MWpvN3RJ
            alFhMmxTV2tBSHV6R0Q3MHorNzhEV0EKLS0tIFJiVDFiNkJoQkNWSW9Jei9SODZu
            UUYxTkxhTTcxTy9vR3VjcUZsUGdyZjAKFQEGE6zki1Fn5H2yIXOR++sgIUNdMv+D
            xvRB65wmh0guLJaI/BS0BYpXdsAGCWNYAUHlXrmttG0kfplIQgc8Og==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-28T20:51:05Z"
    mac: ENC[AES256_GCM,data:L1jKwWv56wUPIpRUONEXrQMBUOpSkUJONRfIFAazbiadaDflRiimOiu9PQa9j9s0XdIoB6ZElep0bSFGdnVcWqJV82w6497HhhBcUL0odyfwqsbXjqBejgs/GgMujeBUicOU7mib0HcmikBEqtDjy+HOguVtoAm5ipkHHMKVkgA=,iv:2ms1wNkodM5fNauY6XDTjcZVDkoxNYzoGbqeK2i5xY0=,tag:8/zQ1uOMibj4AicjaEbWQw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
