apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: supabase
  namespace: supabase
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`supabase.internal.crussell.io`)
      kind: Rule
      services:
        - name: supabase-kong
          port: 8000
  tls:
    certResolver: letsencrypt
