apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcpx
  namespace: mcpx
spec:
  interval: 15m
  chart:
    spec:
      chart: lunar-mcpx
      version: "v0.1.7"
      sourceRef:
        kind: HelmRepository
        name: lunar
        namespace: mcpx
      interval: 1h
  values:
    config:
      appYaml: |
        auth:
          enabled: false
        permissions:
          base: "allow"
        toolExtensions:
          services: {}
    controlPlane:
      host: "mcpx.internal.crussell.io"
      streaming:
        enabled: false
      rest:
        enabled: false
