apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcpx
  namespace: mcpx
spec:
  interval: 15m
  chart:
    spec:
      chart: lunar-mcpx
      version: "v0.1.7"
      sourceRef:
        kind: HelmRepository
        name: lunar
        namespace: mcpx
      interval: 1h
  values:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    config:
      mcpJson: |
        {
          "mcpServers": {
            "memory": {
              "command": "npx",
              "args": [
                "-y",
                "@modelcontextprotocol/server-memory"
              ],
              "env": {
                "MEMORY_FILE_PATH": "/home/lunar/memory.json"
              },
              "icon": "📝"
            },
            "searxng": {
              "command": "npx",
              "args": ["-y", "mcp-searxng"],
              "env": {
                "SEARXNG_URL": "https://searxng.searxng.svc.cluster.local:8080"
              }
            }
          }
        }
      appYaml: |
        auth:
          enabled: false
        permissions:
          base: "allow"
        toolExtensions:
          services: {}
