apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mcpx
  namespace: mcpx
spec:
  interval: 15m
  chart:
    spec:
      chart: lunar-mcpx
      version: "v0.1.7"
      sourceRef:
        kind: HelmRepository
        name: lunar
        namespace: mcpx
      interval: 1h
  values:
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1Gi
    envFrom:
      - secretRef:
          name: mcpx-graphiti-env
    config:
      mcpJson: |
        {
          "mcpServers": {
            "searxng": {
              "command": "npx",
              "args": ["-y", "mcp-searxng"],
              "env": {
                "SEARXNG_URL": "http://searxng.searxng.svc.cluster.local:8080"
              }
            },
            "graphiti-memory": {
              "command": "/usr/bin/uv",
              "args": [
                "run",
                "--with",
                "montesmakes.graphiti-memory",
                "python",
                "-m",
                "graphiti_mcp_server",
                "--transport",
                "stdio",
                "--group-id",
                "default"
              ],
              "env": {
                "NEO4J_URI": "$(NEO4J_URI)",
                "NEO4J_USER": "$(NEO4J_USER)",
                "NEO4J_PASSWORD": "$(NEO4J_PASSWORD)",
                "OPENAI_API_KEY": "$(OPENAI_API_KEY)",
                "OPENAI_BASE_URL": "$(OPENAI_BASE_URL)",
                "MODEL_NAME": "$(MODEL_NAME)",
                "SMALL_MODEL_NAME": "$(SMALL_MODEL_NAME)",
                "GRAPHITI_TELEMETRY_ENABLED": "$(GRAPHITI_TELEMETRY_ENABLED)",
                "SEMAPHORE_LIMIT": "$(SEMAPHORE_LIMIT)"
              }
            }
          }
        }
      appYaml: |
        auth:
          enabled: false
        permissions:
          base: "allow"
        toolExtensions:
          services: {}
