apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mcpx-graphiti
  namespace: mcpx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: longhorn
