apiVersion: apps/v1
kind: Deployment
metadata:
  name: chex-mix-timer
  namespace: chex-mix-timer
  labels:
    app: chex-mix-timer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chex-mix-timer
  template:
    metadata:
      labels:
        app: chex-mix-timer
    spec:
      containers:
        - name: chex-mix-timer
          image: ghcr.io/chad-russell/chex-mix-timer:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chex-mix-timer
  namespace: chex-mix-timer
  labels:
    app: chex-mix-timer
spec:
  selector:
    app: chex-mix-timer
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

