apiVersion: apps/v1
kind: Deployment
metadata:
  name: chex-mix-timer
  namespace: chex-mix-timer
  labels:
    app: chex-mix-timer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chex-mix-timer
  template:
    metadata:
      labels:
        app: chex-mix-timer
    spec:
      containers:
        - name: chex-mix-timer
          # Flux Image Automation will maintain this tag via setter below
          image: ghcr.io/chad-russell/chex-mix-timer:v0.0.4 # {"$imagepolicy": "flux-system:chex-mix-timer"}
          ports:
            - containerPort: 8080
          env:
            - name: REDIS_URL
              value: "redis://redis.infra.svc.cluster.local:6379"
            - name: VAPID_PUBLIC_KEY
              value: "BGpviRcstRBqjCSjDX3rm4AhAzck48BL9EH0T8LhjPi2PuWG2An3p3DmZ2U3iKSl4UF_qX61qDTTdtUcobkwXwM"
            - name: VAPID_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: chex-mix-timer-secrets
                  key: VAPID_PRIVATE_KEY
          livenessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: Host
                  value: chex-mix-timer.crussell.io
            initialDelaySeconds: 15
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 8080
              httpHeaders:
                - name: Host
                  value: chex-mix-timer.crussell.io
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: chex-mix-timer
  namespace: chex-mix-timer
  labels:
    app: chex-mix-timer
spec:
  selector:
    app: chex-mix-timer
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
