apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - nginx-configmap.yaml
  - frontend-deployment.yaml
  - backend-deployment.yaml
  - ingress.yaml
  - secrets.yaml
  - frontend-image-repository.yaml
  - frontend-image-policy.yaml
  - backend-image-repository.yaml
  - backend-image-policy.yaml
  - image-update-automation.yaml
