apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: "3.7.3"
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: media
      interval: 15m
  values:
    controllers:
      radarr:
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/radarr
              tag: "5.28.0" # {"$imagepolicy": "flux-system:radarr"}
            env:
              TZ: "America/New_York" # Change to your timezone
              RADARR__SERVER__PORT: "80"
              RADARR__AUTH__METHOD: "External"
              RADARR__AUTH__REQUIRED: "DisabledForLocalAddresses"
              RADARR__APP__THEME: "dark"
              RADARR__LOG__LEVEL: "info"
              RADARR__APP__INSTANCENAME: "Radarr"
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    defaultPodOptions:
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: radarr
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        storageClass: "longhorn" # Using your Longhorn storage
        accessMode: ReadWriteOnce
        size: 1Gi
        retain: true
        globalMounts:
          - path: /config
      tmp:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /tmp
      media:
        enabled: true
        type: nfs
        server: 192.168.20.31
        path: /mnt/tank/media
        globalMounts:
          - path: /data
