apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`radarr.internal.crussell.io`) # Change this to your domain
      kind: Rule
      services:
        - name: radarr
          port: 80
  tls:
    secretName: internal-wildcard-tls
