apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-temp
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti
  storageClassName: longhorn
