apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-cluster
  namespace: postgres-system
  labels:
    app: postgres-cluster
spec:
  selector:
    matchLabels:
      postgresql: postgres-cluster
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-monitoring-queries
  namespace: postgres-system
data:
  custom-queries.yaml: |
    pg_replication:
      query: "SELECT CASE WHEN NOT pg_is_in_recovery() THEN 0 ELSE GREATEST (0, EXTRACT(EPOCH FROM (now() - pg_last_xact_replay_timestamp()))) END AS lag"
      master: true
      metrics:
        - lag:
            usage: "GAUGE"
            description: "Replication lag behind master in seconds"

    pg_database:
      query: "SELECT pg_database.datname, pg_database_size(pg_database.datname) as size FROM pg_database"
      master: true
      cache_seconds: 30
      metrics:
        - datname:
            usage: "LABEL"
            description: "Name of the database"
        - size:
            usage: "GAUGE"
            description: "Size of the database in bytes"

    pg_locks:
      query: "SELECT mode, locktype, granted, COUNT(*) as count FROM pg_locks WHERE database IS NOT NULL GROUP BY mode, locktype, granted"
      master: true
      cache_seconds: 30
      metrics:
        - mode:
            usage: "LABEL"
            description: "Lock mode"
        - locktype:
            usage: "LABEL"
            description: "Lock type"
        - granted:
            usage: "LABEL"
            description: "Lock granted status"
        - count:
            usage: "GAUGE"
            description: "Number of locks"
