apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cnpg-system
  namespace: postgres-system
spec:
  interval: 24h
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: postgres-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudnative-pg
      version: "0.21.6"
      sourceRef:
        kind: HelmRepository
        name: cnpg-system
        namespace: postgres-system
      interval: 12h
  install:
    createNamespace: true
  upgrade:
    remediation:
      retries: 3
  values:
    # Disable monitoring for now (requires Prometheus operator)
    monitoring:
      enabled: false
      podMonitorEnabled: false
    # Resource limits for the operator
    resources:
      limits:
        cpu: 100m
        memory: 200Mi
      requests:
        cpu: 100m
        memory: 200Mi
