apiVersion: ENC[AES256_GCM,data:rrY=,iv:QV0Cb/1nFJfo0uaF62sgtwdLmTUjHkEtj7UfqjnzYrk=,tag:TmAB3VTzjCl/xHY0WHk/XQ==,type:str]
kind: ENC[AES256_GCM,data:Y0JoArGl,iv:yHBJthnpaaXgkao1NkLnxPJq7PsFBXtFPDjwG6ZGffk=,tag:bDbH9HsNygAFrh4T/5Sdgg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:emdk1qBk+jVWX9I6jyp69q6CFTY=,iv:4FBeN1bG26FNeE31m8PJFlc8d0NMOD4mQ4Jg/glyJrM=,tag:frLwFnzb8quj1cIUM3oP/w==,type:str]
  namespace: ENC[AES256_GCM,data:jdttUQ4Bo8MlOm6KmNNL,iv:uNCHXrUkXO5mytXeASMvrsKaLZ8jBOlvt5fA8ktQPZQ=,tag:x9DlruARzQCSPCEQlfQTMg==,type:str]
type: ENC[AES256_GCM,data:LAig5II2,iv:Ob+FxuaRra1Yrm+NudGS2xEcHh/gA4XdhNCleSwL52s=,tag:JdyJebR/DFWeznbBN6aDpA==,type:str]
stringData:
  #ENC[AES256_GCM,data:AQpqxDXr6ceDrBfgWSVR4wHGeiITq59qbjklg5U8nAqU,iv:isgtE6+Rccd8t8P4c8B7GgBFHiE4+dwOECzDnipgSOM=,tag:xuJ/iZXutlCloQ1kxg8QZQ==,type:comment]
  username: ENC[AES256_GCM,data:6qg029ungZ4=,iv:RMqsFumY95NojyisjTdQxaXUkMr16uwfFaq+T68pO24=,tag:2eiiyUnDX+H+uv9kz87CZw==,type:str]
  password: ENC[AES256_GCM,data:GHjwpgdOgvjoUmM8uEe8BDWyfHk=,iv:UMTvagCYwqC9jFYnvA/oYp5PQ85+yCnqTYcBJ5GoRxs=,tag:zdsPjx4OXhAuwylNSkG3qQ==,type:str]
  #ENC[AES256_GCM,data:WwUTskSSf9rVljVQaDElUHyrfQNH2tqSc1A0laU=,iv:NEyJavff5F3wSzYR3YTAwQN84HJqtpwGHexZjfBxfWg=,tag:sovUpI0so6+PqgBjz9yXEQ==,type:comment]
  app_username: ENC[AES256_GCM,data:N8iIBEdXYO4=,iv:1Oh4xpfPzk4/gduSG2EifM/yI0nS83ZVFldlts1UHEw=,tag:VUkfo8Y8xdhdxOqjCMhsvQ==,type:str]
  app_password: ENC[AES256_GCM,data:6MxOrKOra85q6J6JrKQ8mkoSzb0=,iv:Lk3FnLrG2K2e+FLdgigh79tcYEEiIqNS/Bv+jQRh5rE=,tag:KE42kKpspY9mdgerfwCLlQ==,type:str]
  #ENC[AES256_GCM,data:34ICkUrT8wrLqIZWP/mOO5WGG+GsGm7cUZQ2xGlaOTDHbT4xcp4uve2KqljYKmX1LKOYR+ti,iv:79oMZQ4u1Gt2EjcQuBGaqdr3uQNPCOsS42AvuMEhb7s=,tag:KUJEk94aw3qiFGZ/oQF7lw==,type:comment]
  backup_access_key: ENC[AES256_GCM,data:+yB/hz0QPUWm9zLzcBcv6iTbtI8=,iv:1L43wpandhtRz8TSGGErqM/zyQ2fEznkzMMwzcq/yH4=,tag:+HvlKf+2NkvJNE+F6bD1EQ==,type:str]
  backup_secret_key: ENC[AES256_GCM,data:EFeKNI0o6/c3oKwlK+bPBBYjKgDgRLsbC9q3ff1HoqBj1qLUyJwSgQ==,iv:ftggcbDMUP2Uesdv2aJZzMGZWlqd9MQCVyuqLA3arm0=,tag:rDvBlej26DCu2YS9bAYqDQ==,type:str]
sops:
  age:
    - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OWNsS2ZrREtGejZuc1l1
        dE00YS9oRlFqbm4rajBHVGpjZmFXTVBDVzFJClV2ZEZYN2pFTU9yMUJremRFcWpR
        Q2tvdUFGR04vM3BXQkQ0WjdpcUExb3cKLS0tIGhLQUc3NEl6aWY5OFA5eHZTZkVs
        ZU1IUlNNbFRXNDhNNUNFRndqTTJLZWcK2EAnoM/F2Y7AGrgnhvc8Z1ilg8VmI/Fx
        R/3N8GDDxtP/K0+j4BO5+GFU3ZEYxycxlBtwYv5whld3cYx3yWKRYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-11T00:24:32Z"
  mac: ENC[AES256_GCM,data:ABSinfmL3BFVQsvg4KFq2g44IM5ZeDw6f5/gWxjAwGCseCinRPtC7B7SXsj0VPvsMYvT48hZh8bZn6+FkEXPlre8OaOhLBPeQccGMdM80MR4k8RTPsxm5SkC888oOzvAk4Z1CtP8jUpL7a+7v64FHPzrBFO+wKpKaQd3nlW5uQQ=,iv:D1cT+aByPvnmC3mI1dfN87ZC3hQa1NwizZ/rKeGW0nc=,tag:Do+KNKxNVu5qSWICiiTeeA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
---
apiVersion: ENC[AES256_GCM,data:rrY=,iv:QV0Cb/1nFJfo0uaF62sgtwdLmTUjHkEtj7UfqjnzYrk=,tag:TmAB3VTzjCl/xHY0WHk/XQ==,type:str]
kind: ENC[AES256_GCM,data:Y0JoArGl,iv:yHBJthnpaaXgkao1NkLnxPJq7PsFBXtFPDjwG6ZGffk=,tag:bDbH9HsNygAFrh4T/5Sdgg==,type:str]
metadata:
  name: ENC[AES256_GCM,data:0UJoQ4KsZOqGWhl0XuHX9YH/YrsNQmNVIiVX,iv:qCiv05EY1uYGiPWSHHT80GN9Yj/xG4YWLIqt/TIDu5I=,tag:JL8JXYqbBNSAGSE5aeomyQ==,type:str]
  namespace: ENC[AES256_GCM,data:jdttUQ4Bo8MlOm6KmNNL,iv:uNCHXrUkXO5mytXeASMvrsKaLZ8jBOlvt5fA8ktQPZQ=,tag:x9DlruARzQCSPCEQlfQTMg==,type:str]
type: ENC[AES256_GCM,data:LAig5II2,iv:Ob+FxuaRra1Yrm+NudGS2xEcHh/gA4XdhNCleSwL52s=,tag:JdyJebR/DFWeznbBN6aDpA==,type:str]
stringData:
  #ENC[AES256_GCM,data:AycPqTfSRBhhAsS5ZvG0BYFRIW/bScFN0yV+TCVJ+49jMNdw,iv:uBir982V9mlxeEeIg56/4ew+YQAc6W1RDhvrXQI1SyI=,tag:k4NyhaeAZV519KrNFkBLKw==,type:comment]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:SDTby6ILYF9KLYHk4OYNIKCJkAQ=,iv:q9Ki9SuBzCe6MOCv5FOAkRU0KiSBRCBWDQL5nh0O5w8=,tag:1eG1YOWu5auHSTjxhnwGUA==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:xxSaaYe8WHcT9x6vDFMA+y6ENfyDOPzmPnIBfRCa8P+2YsL9UCNWMw==,iv:Fg3Lh2+FDXnDIke7lKL0avnlcmkS572NCRyvnHTJ8/s=,tag:/bbyL3Zqk14KbIfslTZ/QA==,type:str]
  #ENC[AES256_GCM,data:NamBfwuel2ZepGP6Hd2YnqQZi8lgMQ==,iv:5xcCG1FsNXdhOlj4bdbXgZ05e5YyBKimZty5HQ57M9c=,tag:+DAyGqPBMNfq/Hw7w3LNqQ==,type:comment]
  ENCRYPTION_KEY: ENC[AES256_GCM,data:Z7LFxYMPuWCVRiPMRoxxPEcKsJ7k+YJTH6AsI+xDp9H0hVBIopn/pbWZPVY=,iv:tl2TnjzgObKswvzknkNLHccJIR0oe3Rz2klddNQVDHw=,tag:Dcdnnb0v+RbP6hXN7LQPjQ==,type:str]
sops:
  age:
    - recipient: age1nu5dhecwm2tch3yt4jhx8dwyl2n30sv9072jsuy07mgk6zc83d5spxrg7g
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5OWNsS2ZrREtGejZuc1l1
        dE00YS9oRlFqbm4rajBHVGpjZmFXTVBDVzFJClV2ZEZYN2pFTU9yMUJremRFcWpR
        Q2tvdUFGR04vM3BXQkQ0WjdpcUExb3cKLS0tIGhLQUc3NEl6aWY5OFA5eHZTZkVs
        ZU1IUlNNbFRXNDhNNUNFRndqTTJLZWcK2EAnoM/F2Y7AGrgnhvc8Z1ilg8VmI/Fx
        R/3N8GDDxtP/K0+j4BO5+GFU3ZEYxycxlBtwYv5whld3cYx3yWKRYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-11T00:24:32Z"
  mac: ENC[AES256_GCM,data:ABSinfmL3BFVQsvg4KFq2g44IM5ZeDw6f5/gWxjAwGCseCinRPtC7B7SXsj0VPvsMYvT48hZh8bZn6+FkEXPlre8OaOhLBPeQccGMdM80MR4k8RTPsxm5SkC888oOzvAk4Z1CtP8jUpL7a+7v64FHPzrBFO+wKpKaQd3nlW5uQQ=,iv:D1cT+aByPvnmC3mI1dfN87ZC3hQa1NwizZ/rKeGW0nc=,tag:Do+KNKxNVu5qSWICiiTeeA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
