apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: jellyseerr
  namespace: media
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`jellyseerr.crussell.io`)
      kind: Rule
      services:
        - name: jellyseerr
          port: 5055
  tls:
    certResolver: letsencrypt
