apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr
  namespace: media
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`prowlarr.internal.crussell.io`)
      kind: Rule
      services:
        - name: prowlarr
          port: 80
