apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
resources:
  - namespace.yaml
  - source.yaml
  - release.yaml
  - secrets.yaml
  - cluster-issuer.yaml
  - wildcard-certificate.yaml
  - reflector.yaml