---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: cert-manager
spec:
  interval: 1h
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: reflector
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: reflector
      version: "7.1.288"
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: cert-manager
  values:
    # Configure RBAC permissions
    rbac:
      enabled: true
    
    # Resource limits
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 128Mi
    
    # Security context
    securityContext:
      runAsNonRoot: true
      runAsUser: 65534
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL 