apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 5m
  chart:
    spec:
      chart: cert-manager
      version: "v1.15.1"
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
    extraArgs:
      - --dns01-recursive-nameservers-only
      - --dns01-recursive-nameservers=8.8.8.8:53,1.1.1.1:53
      - --v=4
    
    # Use host networking to bypass NAT rule
    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"
    
    # Remove the custom DNS config since we're using host networking
    # podDnsPolicy: "None"
    # podDnsConfig: ... 