apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: internal-wildcard-cert
  namespace: cert-manager  # Create in cert-manager namespace for cluster-wide access
spec:
  secretName: internal-wildcard-tls
  issuerRef:
    name: letsencrypt-dns
    kind: ClusterIssuer
  dnsNames:
  - "*.internal.crussell.io"
  - "internal.crussell.io"  # Include the root domain too 